### ISSUE TITLE
Краш на iOS 15

### ISSUE THREAD

**Issue by rastaman111** [venvear/ThemeSwitcher#2]
Я заметил что данная реализация крашится при запуске приложения на iPad Pro с 15 iOS, но на 14 все нормально работает

let themeWindow = ThemeWindow() 
Краш на этой строке в AppDelegate

**Comment by rastaman111** [comment]
@raievnov Есть мысли что это может быть?

**Comment by venvear** [comment]
@rastaman111 исправил

**Comment by rastaman111** [comment]
Данное решение не является актуальным, так как UIApplication.shared.windows в iOS 15 устарел
